name: RedisBungee
main: io.minimum.minecraft.redisbungee.RedisBungee
version: 0.4
author: tuxed
# This is used so that we can automagically override default BungeeCord behavior.
softDepends: ["cmd_find", "cmd_list"]